import fs from "node:fs"
import path from "node:path"
import os from "node:os"

const ZENBU_DIR = path.join(os.homedir(), ".zenbu")
const REGISTRY_DIR = path.join(ZENBU_DIR, "registry")

type ServiceEntry = { className: string; key: string; filePath: string }
type SchemaEntry = { name: string; schemaPath: string }

function findManifest(from: string): string | null {
  let dir = path.resolve(from)
  while (true) {
    const candidate = path.join(dir, "zenbu.plugin.json")
    if (fs.existsSync(candidate)) return candidate
    const parent = path.dirname(dir)
    if (parent === dir) return null
    dir = parent
  }
}

function expandGlob(baseDir: string, pattern: string): string[] {
  if (!pattern.includes("*")) {
    const full = path.resolve(baseDir, pattern)
    return fs.existsSync(full) ? [full] : []
  }
  const dir = path.resolve(baseDir, path.dirname(pattern))
  const filePattern = path.basename(pattern)
  const regex = new RegExp(
    "^" + filePattern.replace(/\./g, "\\.").replace(/\*/g, ".*") + "$",
  )
  try {
    return fs
      .readdirSync(dir)
      .filter((f) => regex.test(f))
      .map((f) => path.resolve(dir, f))
  } catch {
    return []
  }
}

function discoverServices(baseDir: string, serviceGlobs: string[]): ServiceEntry[] {
  const entries: ServiceEntry[] = []
  for (const glob of serviceGlobs) {
    for (const filePath of expandGlob(baseDir, glob)) {
      const content = fs.readFileSync(filePath, "utf8")
      const classMatch = content.match(/export\s+class\s+(\w+)\s+extends\s+Service/)
      const keyMatch = content.match(/static\s+key\s*=\s*["']([^"']+)["']/)
      if (classMatch && keyMatch) {
        entries.push({
          className: classMatch[1]!,
          key: keyMatch[1]!,
          filePath,
        })
      }
    }
  }
  return entries
}

function relativeFromRegistry(absPath: string): string {
  let rel = path.relative(REGISTRY_DIR, absPath)
  if (!rel.startsWith(".")) rel = "./" + rel
  return rel.replace(/\.ts$/, "")
}

const SERVICE_BASE_LITERAL = [
  `  | "evaluate"`,
  `  | "shutdown"`,
  `  | "constructor"`,
  `  | "effect"`,
  `  | "__cleanupAllEffects"`,
  `  | "__effectCleanups"`,
  `  | "ctx"`,
].join("\n")

function generateServicesFile(allServices: Map<string, ServiceEntry[]>): string {
  const imports: string[] = []
  const routerEntries: string[] = []
  const usedNames = new Map<string, number>()
  function uniqueName(base: string): string {
    const count = usedNames.get(base) ?? 0
    usedNames.set(base, count + 1)
    return count === 0 ? base : `${base}_${count}`
  }
  for (const [, services] of allServices) {
    for (const svc of services) {
      const alias = uniqueName(svc.className)
      const importPath = relativeFromRegistry(svc.filePath)
      imports.push(
        `import type { ${svc.className}${alias !== svc.className ? ` as ${alias}` : ""} } from "${importPath}"`,
      )
      const quotedKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(svc.key)
        ? svc.key
        : `"${svc.key}"`
      routerEntries.push(`  ${quotedKey}: ExtractRpcMethods<${alias}>`)
    }
  }
  return [
    "// Generated by: zen link",
    "",
    ...imports,
    "",
    `type ServiceBase =\n${SERVICE_BASE_LITERAL}`,
    "",
    "type ExtractRpcMethods<T> = {",
    "  [K in Exclude<keyof T, ServiceBase | `_${string}`> as T[K] extends (",
    "    ...args: any[]",
    "  ) => any",
    "    ? K",
    "    : never]: T[K]",
    "}",
    "",
    "export type ServiceRouter = {",
    ...routerEntries.map((e) => e + ";"),
    "}",
    "",
  ].join("\n")
}

function generateDbSectionsFile(allSchemas: Map<string, SchemaEntry>): string {
  const imports: string[] = []
  const sectionEntries: string[] = []
  const usedAliases = new Map<string, number>()
  function uniqueAlias(base: string): string {
    const count = usedAliases.get(base) ?? 0
    usedAliases.set(base, count + 1)
    return count === 0 ? base : `${base}${count}`
  }
  for (const [, { name, schemaPath }] of allSchemas) {
    const pascal =
      name.replace(/(^|[-_])(\w)/g, (_m, _p, c: string) => c.toUpperCase()) +
      "Root"
    const alias = uniqueAlias(pascal)
    const importPath = relativeFromRegistry(schemaPath)
    imports.push(`import type { SchemaRoot as ${alias} } from "${importPath}"`)
    const quotedName = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)
      ? name
      : `"${name}"`
    sectionEntries.push(`  ${quotedName}: ${alias}`)
  }
  return [
    "// Generated by: zen link",
    "",
    ...imports,
    "",
    "export type DbSections = {",
    ...sectionEntries.map((e) => e + ";"),
    "}",
    "",
    "export type DbRoot = { plugin: DbSections }",
    "",
  ].join("\n")
}

function readExistingRegistry(): {
  services: Map<string, ServiceEntry[]>
  schemas: Map<string, SchemaEntry>
} {
  const services = new Map<string, ServiceEntry[]>()
  const schemas = new Map<string, SchemaEntry>()

  const servicesPath = path.join(REGISTRY_DIR, "services.ts")
  if (fs.existsSync(servicesPath)) {
    const content = fs.readFileSync(servicesPath, "utf8")
    const importRe = /import type \{ (\w+)(?:\s+as\s+(\w+))? \} from "([^"]+)"/g
    const routerRe = /^\s+(?:"([^"]+)"|(\w+)):\s+ExtractRpcMethods<(\w+)>/gm
    const importMap = new Map<string, { className: string; filePath: string }>()
    for (const m of content.matchAll(importRe)) {
      const className = m[1]!
      const alias = m[2] ?? m[1]!
      const relPath = m[3]!
      const absPath = path.resolve(REGISTRY_DIR, relPath) + ".ts"
      importMap.set(alias, { className, filePath: absPath })
    }
    for (const m of content.matchAll(routerRe)) {
      const key = (m[1] ?? m[2])!
      const alias = m[3]!
      const imp = importMap.get(alias)
      if (!imp) continue
      let pluginName: string | null = null
      let dir = path.dirname(imp.filePath)
      while (dir !== path.dirname(dir)) {
        const candidate = path.join(dir, "zenbu.plugin.json")
        if (fs.existsSync(candidate)) {
          try {
            const manifest = JSON.parse(fs.readFileSync(candidate, "utf8"))
            pluginName = manifest.name
          } catch {}
          break
        }
        dir = path.dirname(dir)
      }
      if (!pluginName) continue
      if (!services.has(pluginName)) services.set(pluginName, [])
      services.get(pluginName)!.push({
        className: imp.className,
        key,
        filePath: imp.filePath,
      })
    }
  }

  const dbPath = path.join(REGISTRY_DIR, "db-sections.ts")
  if (fs.existsSync(dbPath)) {
    const content = fs.readFileSync(dbPath, "utf8")
    const importRe = /import type \{ SchemaRoot as (\w+) \} from "([^"]+)"/g
    const sectionRe = /^\s+(?:"([^"]+)"|(\w+)):\s+(\w+)/gm
    const importMap = new Map<string, string>()
    for (const m of content.matchAll(importRe)) {
      const alias = m[1]!
      const relPath = m[2]!
      importMap.set(alias, path.resolve(REGISTRY_DIR, relPath) + ".ts")
    }
    for (const m of content.matchAll(sectionRe)) {
      const name = (m[1] ?? m[2])!
      const alias = m[3]!
      const schemaPath = importMap.get(alias)
      if (schemaPath) schemas.set(name, { name, schemaPath })
    }
  }
  return { services, schemas }
}

export async function runLink(argv: string[]) {
  const explicit = argv.find((a) => !a.startsWith("-"))
  const manifestPath = explicit
    ? path.resolve(explicit)
    : findManifest(process.cwd())
  if (!manifestPath) {
    console.error(
      "Could not find zenbu.plugin.json in current directory or any parent.",
    )
    process.exit(1)
  }

  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"))
  const pluginName = manifest.name
  const baseDir = path.dirname(manifestPath)
  console.log(`Linking plugin "${pluginName}" from ${baseDir}`)

  const serviceEntries = discoverServices(baseDir, manifest.services ?? [])
  console.log(`  Found ${serviceEntries.length} service(s)`)

  const schemaEntry: SchemaEntry | null = manifest.schema
    ? { name: pluginName, schemaPath: path.resolve(baseDir, manifest.schema) }
    : null
  if (schemaEntry) console.log(`  Schema: ${schemaEntry.schemaPath}`)

  const existing = readExistingRegistry()

  existing.services.set(pluginName, serviceEntries)
  if (schemaEntry) existing.schemas.set(pluginName, schemaEntry)

  fs.mkdirSync(REGISTRY_DIR, { recursive: true })
  fs.writeFileSync(
    path.join(REGISTRY_DIR, "services.ts"),
    generateServicesFile(existing.services),
  )
  console.log(`  Wrote registry/services.ts`)
  fs.writeFileSync(
    path.join(REGISTRY_DIR, "db-sections.ts"),
    generateDbSectionsFile(existing.schemas),
  )
  console.log(`  Wrote registry/db-sections.ts`)
  console.log("Done.")
}
